### PR TITLE
PR from DataViking + Fixes from ant

### LINKED ISSUE #50: [Table] tranquil_deposits
Create a table that records all the Deposit Transactions

| block_timestamp     | block_id | user_address | contract_address                           | token_address | token_amount_raw | token_amount | amount_usd |
|---------------------|----------|--------------|--------------------------------------------|---------------|------------------|--------------|------------|
| 2022-01-01 15:00:00 | 25001234 | 0x           | 0x34b9aa82d89ae04f0f546ca5ec9c93efe1288940 | 0x            | 1234567          | 1.234567     | 0.33       |

Hints:
<https://app.tranquil.finance/markets>

## Tranquil's Controller
0x6a82A17B48EF6be278BBC56138F35d04594587E3 

## Token addresses (Just click on the approval to see which contract you're giving the approval to)
ONE - 0x34B9aa82D89AE04f0f546Ca5eC9C93eFE1288940
stOne - 0x973f22036a0ff3a93654e7829444ec64cb37bd78
WBTC - 0xd9c0d8ad06abe10ab29655ff98dcaaa0e059184a
1BTC - 0x481721b918c698ff5f253c56684bac8dca84346c
1ETH - 0xc63ab8c72e636c9961c5e9288b697ec5f0b8e1f7
1USDC - ?
1USDT - ?
1DAI - ?

### LINKED ISSUE #51: [Table] tranquil_withdraws
Create a table that records all the withdraw Transactions

| block_timestamp     | block_id | user_address | contract_address                           | token_address | token_amount_raw | token_amount | amount_usd |
|---------------------|----------|--------------|--------------------------------------------|---------------|------------------|--------------|------------|
| 2022-01-01 15:00:00 | 25001234 | 0x           | 0x34b9aa82d89ae04f0f546ca5ec9c93efe1288940 | 0x            | 1234567          | 1.234567     | 0.33       |

Hints:
<https://app.tranquil.finance/markets>
ONE - 0x34B9aa82D89AE04f0f546Ca5eC9C93eFE1288940
stOne - 0x973f22036a0ff3a93654e7829444ec64cb37bd78
WBTC - 0xd9c0d8ad06abe10ab29655ff98dcaaa0e059184a
1BTC - 0x481721b918c698ff5f253c56684bac8dca84346c
1ETH - 0xc63ab8c72e636c9961c5e9288b697ec5f0b8e1f7
1USDC - ?
1USDT - ?
1DAI - ?

### LINKED ISSUE #52: [Table] tranquil_borrows
EDIT: I've just copied and pasted from a previous issue, might not be cleaned correctly.

Create a table that records all the Borrow Transactions

| block_timestamp     | block_id | user_address | contract_address                           | token_address | token_amount_raw | token_amount | amount_usd |
|---------------------|----------|--------------|--------------------------------------------|---------------|------------------|--------------|------------|
| 2022-01-01 15:00:00 | 25001234 | 0x           | 0x34b9aa82d89ae04f0f546ca5ec9c93efe1288940 | 0x            | 1234567          | 1.234567     | 0.33       |

Hints:
<https://app.tranquil.finance/markets>
ONE - 0x34B9aa82D89AE04f0f546Ca5eC9C93eFE1288940
stOne - 0x973f22036a0ff3a93654e7829444ec64cb37bd78
WBTC - 0xd9c0d8ad06abe10ab29655ff98dcaaa0e059184a
1BTC - 0x481721b918c698ff5f253c56684bac8dca84346c
1ETH - 0xc63ab8c72e636c9961c5e9288b697ec5f0b8e1f7
1USDC - ?
1USDT - ?
1DAI - ?

### LINKED ISSUE #53: [Table] tranquil_repayments
EDIT: I've just copied and pasted from a previous issue, might not be cleaned correctly.

| block_timestamp     | block_id | user_address | contract_address                           | token_address | token_amount_raw | token_amount | amount_usd |
|---------------------|----------|--------------|--------------------------------------------|---------------|------------------|--------------|------------|
| 2022-01-01 15:00:00 | 25001234 | 0x           | 0x34b9aa82d89ae04f0f546ca5ec9c93efe1288940 | 0x            | 1234567          | 1.234567     | 0.33       |

Hints:
<https://app.tranquil.finance/markets>

## Tranquil's Controller
0x6a82A17B48EF6be278BBC56138F35d04594587E3 

## Token addresses (Just click on the approval to see which contract you're giving the approval to)
ONE - 0x34B9aa82D89AE04f0f546Ca5eC9C93eFE1288940
stOne - 0x973f22036a0ff3a93654e7829444ec64cb37bd78
WBTC - 0xd9c0d8ad06abe10ab29655ff98dcaaa0e059184a
1BTC - 0x481721b918c698ff5f253c56684bac8dca84346c
1ETH - 0xc63ab8c72e636c9961c5e9288b697ec5f0b8e1f7
1USDC - ?
1USDT - ?
1DAI - ?

### LINKED ISSUE #59: [Table] Tranquil Daily Supply and Borrow
Table that shows running total of of net Supply and Borrow values by token by day

### PR DESCRIPTION
**Pull request by antonyip**
Closes #50
Closes #51
Closes #52
Closes #53
Closes #59

### CODE REVIEW

File: models/tokenprice/tokenprice_swap_vwap_daily.sql [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+        cluster_by=['block_date', 'token_address']
+        )
+}}
+
+with
+
+-- Assuming these stables have USD value of 1
+stables as (
+    select 
+        token_address
```
Comment (antonyip) [inline models/tokenprice/tokenprice_swap_vwap_daily.sql]: ah, just realized, commas should be at the back

**Comment by drakedanner** [comment]
In the future, let's look to break this many changes into multiple PRs if possible. @chuxinh reviewing this one soon!

**Comment by antonyip** [comment]
dbt seed required to be called on prod when this is merged.

File: data/defikingdoms_dex/tokens.py [hunk 2]
```diff
@@ -54,3 +54,6 @@
 
 if not ('0x6d4f4bc32df561a35c05866051cbe9c92759da29' in dups):
     print('0x6d4f4bc32df561a35c05866051cbe9c92759da29,Lesser Chaos Stone,DFKLCHSST,0')
+
+if not ('0x17f3b5240c4a71a3bbf379710f6fa66b9b51f224' in dups):
+    print ('0x17f3b5240c4a71a3bbf379710f6fa66b9b51f224,Greater Atonement Crystal,DFKGATONECR,0')
```
Comment (chuxinh) [inline data/defikingdoms_dex/tokens.py:59]: add extra line here

File: data/tranquil/tranquil_market_labels.csv [hunk 3]
```diff
@@ -0,0 +1,9 @@
+token_address,token_name,token_symbol,decimals,first_tx
+0x34b9aa82d89ae04f0f546ca5ec9c93efe1288940,HRC20 Tranquil ONE,ONE,18,0x1bab15f513a71a72b687bddfdc31292e8db6561781828f4dc136b7582a6baabf
+0x973f22036a0ff3a93654e7829444ec64cb37bd78,HRC20 Staked One,stONE,18,0x223cdaf8be480d0404fa6c25b04e591fe72a4632b9cf7327aa6206a1accfbfaf
+0xd9c0d8ad06abe10ab29655ff98dcaaa0e059184a,HRC20 Wrapped BTC,1WBTC,8,0xf345fa099df6469593289143616b160985af00eb3955bc4209146f060ea3cf39
+0x481721b918c698ff5f253c56684bac8dca84346c,HRC20 BTC,1BTC,8,0xd01f75a5619bbd1d03cb917e2a196642bce7745569cd42e54d8b221013695c26
+0xc63ab8c72e636c9961c5e9288b697ec5f0b8e1f7,HRC20 ETH,1ETH,18,0xa9fee4cb0183b3fab40e946987cffe15e0880eaf6b654050c2bac8d0eacdb535
+0xca3e902efdb2a410c952fd3e4ac38d7dbdcb8e96,HRC20 USD Coin,1USDC,6,0x874f3acf97d79158f218cf9e200009b66776ec205c59f8eeb8dd7e6217599fc6
+0x7af2430efa179db0e76257e5208bcaf2407b2468,HRC20 Tether USD,1USDT,6,0x51741ffd403da3668cdb2a2ee7f56445350dcc8580e590093ef6d2b12bd09c11
+0x49d95736fe7f1f32e3ee5defc26c95ba22834639,HRC20 Dai Stablecoin,1DAI,18,0x956e60b3b0353e06d7443e6e4422310d7dfafe062d2bec37bb5b63c2d02055f0
```
Comment (chuxinh) [inline data/tranquil/tranquil_market_labels.csv]: add line

File: models/core/tokens.sql [hunk 4]
```diff
@@ -32,6 +38,14 @@ final as (
     select
         * 
     from dfk_tokens
+    -- this is used to filter duplicate / problematic tokens from the dfk list.
+    where TOKEN_ADDRESS not in (select token_address from harmony_explorer_tokens)
```
Comment (chuxinh) [inline models/core/tokens.sql]: lower case?

File: models/tokenprice/tokenprice_swap_vwap_daily.sql [hunk 5]
```diff
@@ -0,0 +1,83 @@
...
+        tx_hash,
+        token0_address as token_address,
+        token0_symbol as token_symbol,
+        (amount0In + amount0Out) as token_amount_raw,
+        tokens.decimals as token_decimals,
+        ((amount0In + amount0Out) / pow(10, tokens.decimals)) as token_amount_norm,
+        (amount1In + amount1Out) as stable_amount_raw,
+        stables.decimals as stable_decimals,
+        ((amount1In + amount1Out) / pow(10, stables.decimals)) as stable_amount_norm
+    from swaps
```
Comment (chuxinh) [inline models/tokenprice/tokenprice_swap_vwap_daily.sql]: where is this swap coming from?

File: models/tokenprice/tokenprice_swap_vwap_daily.sql [hunk 6]
```diff
@@ -0,0 +1,83 @@
...
+final as (
+    select
+        block_date, 
+        token_address, 
+        token_symbol, 
+        (sum(stable_amount_norm) / sum(token_amount_norm)) as usd_price, 
+        sum(stable_amount_norm) as usd_24h_volume
+    from bothswaps
+    group by 1,2,3
+    order by block_date
```
Comment (chuxinh) [inline models/tokenprice/tokenprice_swap_vwap_daily.sql]: no need to order here if you have the cluster by above

File: models/tranquil/tranquil_markets_tokenprice.sql [hunk 7]
```diff
@@ -0,0 +1,29 @@
...
+        materialized='table',
+        unique_key="token_symbol||'-'||timestamp",
+        tags=['core', 'defi', 'amm', 'lending']
+        )
+}}
+
+
+with
+final as (  
+    select 'ONE' as token_symbol, * from tokenprice_one
```
Comment (chuxinh) [inline models/tranquil/tranquil_markets_tokenprice.sql]: need to use {{ ref("tokenprice_one") }} and for all of the following
otherwise i think dbt would throw an error

File: models/tranquil/tranquil_txs.sql [hunk 8]
```diff
@@ -0,0 +1,131 @@
...
+    select
+        *
+    from {{ ref('tranquil_market_labels') }}
+),
+
+-- Tranquil contracts all have the same "Creator" or admin address
+tranquil_contracts as (
+    select distinct
+        evm_contract_address
+    from logs
```
Comment (chuxinh) [inline models/tranquil/tranquil_txs.sql:21]: {{ ref('logs') }}

Comment (chuxinh) [reply models/tranquil/tranquil_txs.sql:21]: also is this materialised as a table, as in it will run a full refresh every single time or it should be an incremental build?

File: models/tranquil/tranquil_txs.sql [hunk 9]
```diff
@@ -0,0 +1,131 @@
...
+        *
+    from {{ ref('tranquil_market_labels') }}
+),
+
+-- Tranquil contracts all have the same "Creator" or admin address
+tranquil_contracts as (
+    select distinct
+        evm_contract_address
+    from logs 
+    where event_inputs:admin::string = '0x15424ab0bbab79bad32ce779197748485b5ae456'
```
Comment (chuxinh) [inline models/tranquil/tranquil_txs.sql:22]: maybe leave a comment here on what this iss

File: models/tranquil/tranquil_txs.sql [hunk 10]
```diff
@@ -0,0 +1,131 @@
...
+        logs.tx_hash,
+        block_timestamp,
+        block_id,
+        event_inputs:minter::string as user_address,
+        logs.evm_contract_address,
+        tml.token_symbol,
+        (event_inputs:mintAmount::number) as token_amount_raw,
+        (event_inputs:mintAmount::number / pow(10, tml.decimals)) as token_amount,
+        'Deposit' as tx_type
+    from logs
```
Comment (chuxinh) [inline models/tranquil/tranquil_txs.sql:43]: {{ ref('logs') }}

File: models/tranquil/tranquil_txs.sql [hunk 11]
```diff
@@ -0,0 +1,131 @@
...
+    from {{ ref('tranquil_markets_tokenprice') }}
+),
+
+tranquil_deposits as (
+    select 
+        logs.log_id,
+        logs.tx_hash,
+        block_timestamp,
+        block_id,
+        event_inputs:minter::string as user_address,
```
Comment (chuxinh) [inline models/tranquil/tranquil_txs.sql:37]: probably better to specify what the table here for these columns too

File: models/tranquil/tranquil_txs.sql [hunk 12]
```diff
@@ -0,0 +1,131 @@
...
+        (event_inputs:borrowAmount::number) as token_amount_raw,
+        (event_inputs:borrowAmount::number / pow(10, tml.decimals)) as token_amount,
+        'Borrow' as tx_type
+    from logs 
+    inner join tranquil_contracts as tc 
+        on logs.evm_contract_address = tc.evm_contract_address
+    left join tranquil_market_labels as tml
+        on logs.evm_contract_address = tml.token_address
+    where logs.event_name = 'Borrow'
+),
```
Comment (chuxinh) [inline models/tranquil/tranquil_txs.sql:69]: can this and the following be all combined in one with event_name including all mint, borrow etc, and use case when for `tx_type`?

File: models/tranquil/tranquil_txs.sql [hunk 13]
```diff
@@ -0,0 +1,131 @@
...
+    union all
+    select * from tranquil_withdrawals
+),
+
+final as (
+    select 
+        c.*,
+        (usd.price * c.token_amount) as amount_usd
+    from combined as c
+    left join tranquil_markets_usd usd
```
Comment (chuxinh) [inline models/tranquil/tranquil_txs.sql:126]:
```suggestion
    left join tranquil_markets_usd as usd 
```

File: models/tranquil/tranquil_txs.yml [hunk 14]
```diff
@@ -0,0 +1,61 @@
...
+        tests:
+          - not_null
+      
+      - name: block_id
+        description: The block number.
+        tests:
+          - not_null
+
+      - name: user_address
+        description: The account which deposited to Tranquil.
```
Comment (chuxinh) [inline models/tranquil/tranquil_txs.yml:31]: maybe use `The account which transacted with Tranquil.`

File: models/tranquil/tranquil_daily_supply_borrow.sql [hunk 15]
```diff
@@ -0,0 +1,116 @@
...
+        on m.block_date = t4.block_date
+        and m.token_symbol = t4.token_symbol
+        and t4.tx_type = 'Repayment'
+),
+
+backfill_tvl as (
+
+    select 
+        tml.token_symbol,
+        '2021-12-06 00:00:00.000' as block_date,
```
Comment (chuxinh) [inline models/tranquil/tranquil_daily_supply_borrow.sql]: add a comment on why setting this date?

File: models/tranquil/tranquil_daily_supply_borrow.sql [hunk 16]
```diff
@@ -0,0 +1,116 @@
...
+        0 as price,
+        ( (l.event_inputs:cashPrior + l.event_inputs:totalBorrows) / pow(10,tml.decimals) ) as net_supplied_token_chg,
+        (l.event_inputs:totalBorrows / pow(10,tml.decimals) ) as net_borrowed_token_chg
+    from tranquil_market_labels tml
+    left join logs l
```
Comment (chuxinh) [inline models/tranquil/tranquil_daily_supply_borrow.sql]: use the ref format

File: models/tranquil/tranquil_daily_supply_borrow.sql [hunk 17]
```diff
@@ -0,0 +1,116 @@
...
+
+backfill_tvl as (
+
+    select 
+        tml.token_symbol,
+        '2021-12-06 00:00:00.000' as block_date,
+        0 as price,
+        ( (l.event_inputs:cashPrior + l.event_inputs:totalBorrows) / pow(10,tml.decimals) ) as net_supplied_token_chg,
+        (l.event_inputs:totalBorrows / pow(10,tml.decimals) ) as net_borrowed_token_chg
+    from tranquil_market_labels tml
```
Comment (chuxinh) [inline models/tranquil/tranquil_daily_supply_borrow.sql]:
```suggestion
    from tranquil_market_labels as tml
```

File: models/tranquil/tranquil_daily_supply_borrow.sql [hunk 18]
```diff
@@ -0,0 +1,116 @@
...
+),
+
+deltas as (
+    select 
+        c.token_symbol,
+        c.block_date,
+        c.price,
+        (c.deposit_token_amt - c.withdrawal_token_amt) as net_supplied_token_chg,
+        (c.borrow_token_amt - c.repayment_token_amt) as net_borrowed_token_chg
+    from txns_typecols c
```
Comment (chuxinh) [inline models/tranquil/tranquil_daily_supply_borrow.sql]:
```suggestion
    from txns_typecols as c
```

File: models/tranquil/tranquil_daily_supply_borrow.sql [hunk 19]
```diff
@@ -0,0 +1,116 @@
...
+),
+
+final as (
+    select r.*,
+        (net_supplied_token_chg * price) as net_supplied_usd_chg,
+        (net_borrowed_token_chg * price) as net_borrowed_usd_chg,
+        (running_total_supplied_token * price) as running_total_supplied_usd,
+        (running_total_borrowed_token * price) as running_total_borrowed_usd
+    from running as r
+    order by 1,2
```
Comment (chuxinh) [inline models/tranquil/tranquil_daily_supply_borrow.sql]: no need to order by if you have cluster by above

**Review by chuxinh — CHANGES_REQUESTED** [review]

File: data/tranquil/tranquil_market_labels.csv (hunk 3 above)
Comment (tonykau1) [reply data/tranquil/tranquil_market_labels.csv]: sorry, i don't understand where/what line should be added here, can you please clarify @chuxinh ?

File: models/tokenprice/tokenprice_swap_vwap_daily.sql (hunk 5 above)
Comment (tonykau1) [reply models/tokenprice/tokenprice_swap_vwap_daily.sql]: the tokenprice_swap_vwap_daily model was my attempt at pulling all the prices from direct dex swaps, however most markets were too illiquid to be usable.  Instead of using this approach, i used tranquil_markets_tokenprice which is derived from the most liquid pool path i could find to a stable (e.g. for stONE, it's stONE -> ONE -> USDC, but for ETH it's 1ETH -> JEWEL -> USDC)

We could (should) remove this model for this commit and no functionality will be impacted.

**Comment by tonykau1** [comment]
@chuxinh thank you for the feedback!  Please see my updates on the latest commit.

File: data/tranquil/tranquil_market_labels.csv (hunk 3 above)
Comment (tonykau1) [reply data/tranquil/tranquil_market_labels.csv]: nm, got it - csvs need to end with a new line

File: models/tranquil/tranquil_daily_supply_borrow.sql [hunk 20]
```diff
@@ -100,7 +100,7 @@ running as (
                     and c.block_date >= d2.block_date
         ) as running_total_borrowed_token
     from add_backfill as c
-    order by 1,2
+    --order by 1,2
```
Comment (chuxinh) [inline models/tranquil/tranquil_daily_supply_borrow.sql]: better to delete the line instead of commenting out?

File: models/tranquil/tranquil_daily_supply_borrow.sql [hunk 21]
```diff
@@ -110,7 +110,7 @@ final as (
         (running_total_supplied_token * price) as running_total_supplied_usd,
         (running_total_borrowed_token * price) as running_total_borrowed_usd
     from running as r
-    order by 1,2
+    --order by 1,2
```
Comment (chuxinh) [inline models/tranquil/tranquil_daily_supply_borrow.sql]: same for here as well

**Review by chuxinh — APPROVED** [review]
LGTM after nits.

Thanks so much for addressing all the changes!
